/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/FdpTs9dKD1I
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Button } from "@/components/ui/button";
import Image from "next/image";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";

export function AdminProducts() {
  return (
    <div key="1" className="flex flex-col min-h-screen">
      <header className="bg-white text-gray-900 py-4 px-6 flex items-center">
        <Link className="flex items-center gap-2" href="#">
          <ArrowLeftIcon className="w-5 h-5" />
          <span>Volver</span>
        </Link>
        <h1 className="text-xl font-bold ml-auto text-center">
          Editar Productos
        </h1>
        <Button className="ml-4" variant="primary">
          Agregar Producto
        </Button>
      </header>
      <main className="flex-1 bg-gray-100 dark:bg-gray-800 p-6">
        <div className="max-w-4xl mx-auto">
          <div className="bg-white dark:bg-gray-900 rounded-lg shadow-md overflow-hidden">
            <div className="grid grid-cols-1 md:grid-cols-2">
              <div className="p-6">
                <h2 className="text-2xl font-bold mb-4">Productos</h2>
                <div className="divide-y divide-gray-200 dark:divide-gray-700">
                  <div className="py-4 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                      <Image
                        alt="Producto 1"
                        className="rounded-md"
                        height={64}
                        src="/placeholder.svg"
                        style={{
                          aspectRatio: "64/64",
                          objectFit: "cover",
                        }}
                        width={64}
                      />
                      <div>
                        <h3 className="font-medium text-gray-900 dark:text-gray-100">
                          Producto 1
                        </h3>
                        <p className="text-gray-500 dark:text-gray-400">
                          $19.99
                        </p>
                        <span className="bg-blue-100 text-blue-800 text-xs font-medium px-2 py-0.5 rounded dark:bg-blue-200 dark:text-blue-900">
                          Categoría 1
                        </span>
                        <div className="flex items-center gap-2 mt-2">
                          <CircleCheckIcon className="w-5 h-5 text-green-500" />
                          <CircleCheckIcon className="w-5 h-5 text-green-500" />
                          <CircleCheckIcon className="w-5 h-5 text-green-500" />
                          <CircleCheckIcon className="w-5 h-5 text-green-500" />
                          <CircleCheckIcon className="w-5 h-5 text-green-500" />
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="bg-green-100 text-green-800 text-xs font-medium px-2 py-0.5 rounded dark:bg-green-200 dark:text-green-900">
                        Visible
                      </span>
                      <span className="bg-blue-100 text-blue-800 text-xs font-medium px-2 py-0.5 rounded dark:bg-blue-200 dark:text-blue-900">
                        Especial
                      </span>
                      <Button
                        className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-100"
                        size="icon"
                        variant="outline"
                      >
                        <DeleteIcon className="w-5 h-5" />
                      </Button>
                    </div>
                  </div>
                  <div className="py-4 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                      <Image
                        alt="Producto 2"
                        className="rounded-md"
                        height={64}
                        src="/placeholder.svg"
                        style={{
                          aspectRatio: "64/64",
                          objectFit: "cover",
                        }}
                        width={64}
                      />
                      <div>
                        <h3 className="font-medium text-gray-900 dark:text-gray-100">
                          Producto 2
                        </h3>
                        <p className="text-gray-500 dark:text-gray-400">
                          $29.99
                        </p>
                        <span className="bg-green-100 text-green-800 text-xs font-medium px-2 py-0.5 rounded dark:bg-green-200 dark:text-green-900">
                          Categoría 2
                        </span>
                        <div className="flex items-center gap-2 mt-2">
                          <CircleCheckIcon className="w-5 h-5 text-green-500" />
                          <CircleCheckIcon className="w-5 h-5 text-green-500" />
                          <CircleXIcon className="w-5 h-5 text-red-500" />
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="bg-green-100 text-green-800 text-xs font-medium px-2 py-0.5 rounded dark:bg-green-200 dark:text-green-900">
                        Visible
                      </span>
                      <span className="bg-red-100 text-red-800 text-xs font-medium px-2 py-0.5 rounded dark:bg-red-200 dark:text-red-900">
                        Agotado
                      </span>
                      <Button
                        className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-100"
                        size="icon"
                        variant="outline"
                      >
                        <DeleteIcon className="w-5 h-5" />
                      </Button>
                    </div>
                  </div>
                  <div className="py-4 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                      <Image
                        alt="Producto 3"
                        className="rounded-md"
                        height={64}
                        src="/placeholder.svg"
                        style={{
                          aspectRatio: "64/64",
                          objectFit: "cover",
                        }}
                        width={64}
                      />
                      <div>
                        <h3 className="font-medium text-gray-900 dark:text-gray-100">
                          Producto 3
                        </h3>
                        <p className="text-gray-500 dark:text-gray-400">
                          $39.99
                        </p>
                        <span className="bg-yellow-100 text-yellow-800 text-xs font-medium px-2 py-0.5 rounded dark:bg-yellow-200 dark:text-yellow-900">
                          Categoría 3
                        </span>
                        <div className="flex items-center gap-2 mt-2">
                          <CircleXIcon className="w-5 h-5 text-red-500" />
                          <CircleCheckIcon className="w-5 h-5 text-green-500" />
                          <CircleCheckIcon className="w-5 h-5 text-green-500" />
                        </div>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="bg-red-100 text-red-800 text-xs font-medium px-2 py-0.5 rounded dark:bg-red-200 dark:text-red-900">
                        Agotado
                      </span>
                      <Button
                        className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-100"
                        size="icon"
                        variant="outline"
                      >
                        <DeleteIcon className="w-5 h-5" />
                      </Button>
                    </div>
                  </div>
                </div>
              </div>
              <div className="bg-gray-100 dark:bg-gray-800 p-6">
                <h2 className="text-2xl font-bold mb-4">Editar Producto</h2>
                <form className="grid gap-4">
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label htmlFor="title">Título</Label>
                      <Input defaultValue="Producto 1" id="title" />
                    </div>
                    <div>
                      <Label htmlFor="price">Precio</Label>
                      <Input defaultValue={19.99} id="price" type="number" />
                    </div>
                  </div>
                  <div>
                    <Label htmlFor="description">Descripción</Label>
                    <Textarea id="description" rows={3}>
                      Descripción del producto 1
                    </Textarea>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label
                        className="flex items-center gap-2"
                        htmlFor="special"
                      >
                        <Checkbox defaultChecked id="special" />
                        Especial
                      </Label>
                    </div>
                    <div>
                      <Label className="block mb-1" htmlFor="category">
                        Categoría
                      </Label>
                      <Select defaultValue="categoria1" id="category">
                        <SelectTrigger className="w-full">
                          <SelectValue placeholder="Selecciona una categoría" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="categoria1">
                            Categoría 1
                          </SelectItem>
                          <SelectItem value="categoria2">
                            Categoría 2
                          </SelectItem>
                          <SelectItem value="categoria3">
                            Categoría 3
                          </SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <Label
                        className="flex items-center gap-2"
                        htmlFor="visible"
                      >
                        <Checkbox defaultChecked id="visible" />
                        Visible
                      </Label>
                    </div>
                    <div>
                      <Label
                        className="flex items-center gap-2"
                        htmlFor="outOfStock"
                      >
                        <Checkbox id="outOfStock" />
                        Agotado
                      </Label>
                    </div>
                  </div>
                  <div className="flex justify-end gap-2">
                    <Button variant="outline">Cancelar</Button>
                    <Button>Guardar</Button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

function ArrowLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  );
}

function CircleCheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  );
}

function CircleXIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m15 9-6 6" />
      <path d="m9 9 6 6" />
    </svg>
  );
}

function DeleteIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 5H9l-7 7 7 7h11a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2Z" />
      <line x1="18" x2="12" y1="9" y2="15" />
      <line x1="12" x2="18" y1="9" y2="15" />
    </svg>
  );
}
