/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/BJN3E7JGy5T
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import Link from "next/link";
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { SheetTrigger, SheetContent, Sheet } from "@/components/ui/sheet";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import Image from "next/image";

export function AllProduct() {
  return (
    <div key="1" className="container mx-auto px-6 py-8">
      <header className="flex h-20 w-full shrink-0 items-center px-4 md:px-6">
        <Link
          className="flex items-center gap-2 text-gray-900 font-semibold text-xl"
          href="#"
        >
          <StoreIcon className="h-6 w-6" />
          <span>Acme WebShop</span>
        </Link>
        <div className="hidden lg:flex items-center space-x-4 ml-auto">
          <Link className="text-gray-600 hover:text-gray-900" href="#">
            Home
          </Link>
          <Link className="text-gray-900 font-semibold" href="#">
            Products
          </Link>
          <Link className="text-gray-600 hover:text-gray-900" href="#">
            About
          </Link>
          <Link className="text-gray-600 hover:text-gray-900" href="#">
            Reservation
          </Link>
          <Select>
            <SelectTrigger className="text-gray-600 hover:text-gray-900">
              <SelectValue>USD</SelectValue>
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="usd">USD</SelectItem>
              <SelectItem value="eur">EUR</SelectItem>
              <SelectItem value="gbp">GBP</SelectItem>
            </SelectContent>
          </Select>
          <div className="flex-1 flex items-center justify-end space-x-4">
            <Button className="rounded-full" size="icon" variant="outline">
              <SearchIcon className="w-4 h-4" />
              <span className="sr-only">Search</span>
            </Button>
            <Button className="rounded-full" size="icon" variant="outline">
              <ShoppingCartIcon className="w-4 h-4" />
              <span className="sr-only">Cart</span>
            </Button>
          </div>
          <Button className="rounded-full" size="icon" variant="outline">
            <ShoppingCartIcon className="w-4 h-4" />
            <span className="sr-only">Cart</span>
          </Button>
        </div>
        <Sheet>
          <SheetTrigger asChild>
            <Button className="ml-auto lg:hidden" size="icon" variant="outline">
              <MenuIcon className="h-6 w-6" />
              <span className="sr-only">Toggle navigation menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="right">
            <Link className="flex items-center gap-2" href="#">
              <StoreIcon className="h-6 w-6" />
              <span className="font-semibold text-xl">Acme WebShop</span>
            </Link>
            <div className="grid gap-2 py-6">
              <Link
                className="flex w-full items-center py-2 text-lg font-semibold"
                href="#"
              >
                Home
              </Link>
              <Link
                className="flex w-full items-center py-2 text-lg font-semibold"
                href="#"
              >
                Products
              </Link>
              <Link
                className="flex w-full items-center py-2 text-lg font-semibold"
                href="#"
              >
                About
              </Link>
              <Link
                className="flex w-full items-center py-2 text-lg font-semibold"
                href="#"
              >
                Reservation
              </Link>
            </div>
          </SheetContent>
        </Sheet>
      </header>
      <div className="mt-12">
        <div className="flex flex-col md:flex-row items-start md:items-center justify-between mb-6">
          <div className="grid gap-2">
            <h2 className="text-2xl font-bold">Electronics</h2>
            <div className="flex space-x-4">
              <Link className="text-gray-600 hover:text-gray-900" href="#">
                Electronics
              </Link>
              <Link className="text-gray-600 hover:text-gray-900" href="#">
                Home Goods
              </Link>
              <Link className="text-gray-600 hover:text-gray-900" href="#">
                Apparel
              </Link>
            </div>
          </div>
        </div>
        <div>
          <div
            className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6"
            id="electronics"
          >
            <Card className="w-full">
              <Image
                alt="Product image"
                className="w-full h-48 object-cover"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <div className="p-4">
                <div className="flex justify-between items-center">
                  <h5 className="text-lg font-bold">Wireless Headphones</h5>
                  <Badge
                    className="hover:bg-gray-100/50 dark:hover:bg-gray-800/50"
                    variant="secondary"
                  >
                    Electronics
                  </Badge>
                </div>
                <p className="mt-1 text-gray-600">
                  High-quality wireless headphones with noise-cancelling
                  technology.
                </p>
                <div className="flex justify-between items-center mt-4">
                  <span className="text-lg font-bold">$99.99</span>
                  <Button>Add to Cart</Button>
                </div>
              </div>
            </Card>
            <Card className="w-full">
              <Image
                alt="Product image"
                className="w-full h-48 object-cover"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <div className="p-4">
                <div className="flex justify-between items-center">
                  <h5 className="text-lg font-bold">Smartwatch</h5>
                  <Badge
                    className="hover:bg-gray-100/50 dark:hover:bg-gray-800/50"
                    variant="secondary"
                  >
                    Electronics
                  </Badge>
                </div>
                <p className="mt-1 text-gray-600">
                  Sleek and stylish smartwatch with advanced fitness tracking.
                </p>
                <div className="flex justify-between items-center mt-4">
                  <span className="text-lg font-bold">$199.99</span>
                  <Button>Add to Cart</Button>
                </div>
              </div>
            </Card>
            <Card className="w-full">
              <Image
                alt="Product image"
                className="w-full h-48 object-cover"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <div className="p-4">
                <div className="flex justify-between items-center">
                  <h5 className="text-lg font-bold">Fitness Tracker</h5>
                  <Badge
                    className="hover:bg-gray-100/50 dark:hover:bg-gray-800/50"
                    variant="secondary"
                  >
                    Electronics
                  </Badge>
                </div>
                <p className="mt-1 text-gray-600">
                  Compact and lightweight fitness tracker with heart rate
                  monitoring.
                </p>
                <div className="flex justify-between items-center mt-4">
                  <span className="text-lg font-bold">$79.99</span>
                  <Button>Add to Cart</Button>
                </div>
              </div>
            </Card>
            <Card className="w-full">
              <Image
                alt="Product image"
                className="w-full h-48 object-cover"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <div className="p-4">
                <div className="flex justify-between items-center">
                  <h5 className="text-lg font-bold">Bluetooth Speaker</h5>
                  <Badge
                    className="hover:bg-gray-100/50 dark:hover:bg-gray-800/50"
                    variant="secondary"
                  >
                    Electronics
                  </Badge>
                </div>
                <p className="mt-1 text-gray-600">
                  Powerful and portable Bluetooth speaker with long-lasting
                  battery.
                </p>
                <div className="flex justify-between items-center mt-4">
                  <span className="text-lg font-bold">$59.99</span>
                  <Button>Add to Cart</Button>
                </div>
              </div>
            </Card>
            <Card className="w-full">
              <Image
                alt="Product image"
                className="w-full h-48 object-cover"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <div className="p-4">
                <div className="flex justify-between items-center">
                  <h5 className="text-lg font-bold">Wireless Earbuds</h5>
                  <Badge
                    className="hover:bg-gray-100/50 dark:hover:bg-gray-800/50"
                    variant="secondary"
                  >
                    Electronics
                  </Badge>
                </div>
                <p className="mt-1 text-gray-600">
                  Truly wireless earbuds with advanced noise-cancelling
                  technology.
                </p>
                <div className="flex justify-between items-center mt-4">
                  <span className="text-lg font-bold">$129.99</span>
                  <Button>Add to Cart</Button>
                </div>
              </div>
            </Card>
            <Card className="w-full">
              <Image
                alt="Product image"
                className="w-full h-48 object-cover"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <div className="p-4">
                <div className="flex justify-between items-center">
                  <h5 className="text-lg font-bold">Wireless Charging Pad</h5>
                  <Badge
                    className="hover:bg-gray-100/50 dark:hover:bg-gray-800/50"
                    variant="secondary"
                  >
                    Electronics
                  </Badge>
                </div>
                <p className="mt-1 text-gray-600">
                  Sleek and efficient wireless charging pad for your devices.
                </p>
                <div className="flex justify-between items-center mt-4">
                  <span className="text-lg font-bold">$39.99</span>
                  <Button>Add to Cart</Button>
                </div>
              </div>
            </Card>
          </div>
          <div
            className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 mt-12"
            id="home-goods"
          >
            <Card className="w-full">
              <Image
                alt="Product image"
                className="w-full h-48 object-cover"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <div className="p-4">
                <div className="flex justify-between items-center">
                  <h5 className="text-lg font-bold">Cozy Throw Blanket</h5>
                  <Badge
                    className="hover:bg-gray-100/50 dark:hover:bg-gray-800/50"
                    variant="secondary"
                  >
                    Home Goods
                  </Badge>
                </div>
                <p className="mt-1 text-gray-600">
                  Soft and plush throw blanket to keep you warm and cozy.
                </p>
                <div className="flex justify-between items-center mt-4">
                  <span className="text-lg font-bold">$49.99</span>
                  <Button>Add to Cart</Button>
                </div>
              </div>
            </Card>
            <Card className="w-full">
              <Image
                alt="Product image"
                className="w-full h-48 object-cover"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <div className="p-4">
                <div className="flex justify-between items-center">
                  <h5 className="text-lg font-bold">Ceramic Vase</h5>
                  <Badge
                    className="hover:bg-gray-100/50 dark:hover:bg-gray-800/50"
                    variant="secondary"
                  >
                    Home Goods
                  </Badge>
                </div>
                <p className="mt-1 text-gray-600">
                  Elegant and modern ceramic vase for your home decor.
                </p>
                <div className="flex justify-between items-center mt-4">
                  <span className="text-lg font-bold">$29.99</span>
                  <Button>Add to Cart</Button>
                </div>
              </div>
            </Card>
            <Card className="w-full">
              <Image
                alt="Product image"
                className="w-full h-48 object-cover"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <div className="p-4">
                <div className="flex justify-between items-center">
                  <h5 className="text-lg font-bold">Scented Candle</h5>
                  <Badge
                    className="hover:bg-gray-100/50 dark:hover:bg-gray-800/50"
                    variant="secondary"
                  >
                    Home Goods
                  </Badge>
                </div>
                <p className="mt-1 text-gray-600">
                  Soy-based candle with a relaxing and calming fragrance.
                </p>
                <div className="flex justify-between items-center mt-4">
                  <span className="text-lg font-bold">$19.99</span>
                  <Button>Add to Cart</Button>
                </div>
              </div>
            </Card>
            <Card className="w-full">
              <Image
                alt="Product image"
                className="w-full h-48 object-cover"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <div className="p-4">
                <div className="flex justify-between items-center">
                  <h5 className="text-lg font-bold">Decorative Pillow</h5>
                  <Badge
                    className="hover:bg-gray-100/50 dark:hover:bg-gray-800/50"
                    variant="secondary"
                  >
                    Home Goods
                  </Badge>
                </div>
                <p className="mt-1 text-gray-600">
                  Soft and plush decorative pillow to add style to your space.
                </p>
                <div className="flex justify-between items-center mt-4">
                  <span className="text-lg font-bold">$24.99</span>
                  <Button>Add to Cart</Button>
                </div>
              </div>
            </Card>
            <Card className="w-full">
              <Image
                alt="Product image"
                className="w-full h-48 object-cover"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <div className="p-4">
                <div className="flex justify-between items-center">
                  <h5 className="text-lg font-bold">Ceramic Planter</h5>
                  <Badge
                    className="hover:bg-gray-100/50 dark:hover:bg-gray-800/50"
                    variant="secondary"
                  >
                    Home Goods
                  </Badge>
                </div>
                <p className="mt-1 text-gray-600">
                  Stylish and durable ceramic planter for your indoor plants.
                </p>
                <div className="flex justify-between items-center mt-4">
                  <span className="text-lg font-bold">$34.99</span>
                  <Button>Add to Cart</Button>
                </div>
              </div>
            </Card>
            <Card className="w-full">
              <Image
                alt="Product image"
                className="w-full h-48 object-cover"
                height="200"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "200/200",
                  objectFit: "cover",
                }}
                width="200"
              />
              <div className="p-4">
                <div className="flex justify-between items-center">
                  <h5 className="text-lg font-bold">Woven Basket</h5>
                  <Badge
                    className="hover:bg-gray-100/50 dark:hover:bg-gray-800/50"
                    variant="secondary"
                  >
                    Home Goods
                  </Badge>
                </div>
                <p className="mt-1 text-gray-600">
                  Handwoven storage basket for organizing your space.
                </p>
                <div className="flex justify-between items-center mt-4">
                  <span className="text-lg font-bold">$39.99</span>
                  <Button>Add to Cart</Button>
                </div>
              </div>
            </Card>
          </div>
          <div
            className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 mt-12"
            id="apparel"
          >
            <Card className="w-full" />
          </div>
        </div>
      </div>
    </div>
  );
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}

function ShoppingCartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="8" cy="21" r="1" />
      <circle cx="19" cy="21" r="1" />
      <path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12" />
    </svg>
  );
}

function StoreIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m2 7 4.41-4.41A2 2 0 0 1 7.83 2h8.34a2 2 0 0 1 1.42.59L22 7" />
      <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
      <path d="M15 22v-4a2 2 0 0 0-2-2h-2a2 2 0 0 0-2 2v4" />
      <path d="M2 7h20" />
      <path d="M22 7v3a2 2 0 0 1-2 2v0a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 16 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 12 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 8 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 4 12v0a2 2 0 0 1-2-2V7" />
    </svg>
  );
}
