/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/6odkrcsg9l0
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'
import { Arimo } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import Image from "next/image";
import {
  DropdownMenuTrigger,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenu,
} from "@/components/ui/dropdown-menu";

export function BoulevardPage() {
  return (
    <div className="w-full max-w-6xl mx-auto py-8 px-4 md:px-6">
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold">Boulevard de Tiendas</h1>
        <div className="relative w-full max-w-md">
          <Input
            className="pr-10"
            placeholder="Buscar tiendas..."
            type="search"
          />
          <SearchIcon className="absolute right-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-500 dark:text-gray-400" />
        </div>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
        <div className="bg-white rounded-lg shadow-md dark:bg-gray-900">
          <div className="p-4">
            <div className="flex items-center mb-2">
              <Image
                alt="Logo"
                className="rounded-full mr-3"
                height={40}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width={40}
              />
              <div>
                <h3 className="text-lg font-medium">Tienda de Ropa</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Ropa y Accesorios
                </p>
              </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Descubre una amplia selección de ropa y accesorios de moda en
              nuestra tienda.
            </p>
            <Link
              className="inline-flex items-center justify-center px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-500 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200 dark:focus:ring-gray-300"
              href="#"
            >
              Ver más
            </Link>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md dark:bg-gray-900">
          <div className="p-4">
            <div className="flex items-center mb-2">
              <Image
                alt="Logo"
                className="rounded-full mr-3"
                height={40}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width={40}
              />
              <div>
                <h3 className="text-lg font-medium">Librería</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Libros y Papelería
                </p>
              </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Encuentra una amplia selección de libros, revistas y artículos de
              papelería.
            </p>
            <Link
              className="inline-flex items-center justify-center px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-500 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200 dark:focus:ring-gray-300"
              href="#"
            >
              Ver más
            </Link>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md dark:bg-gray-900">
          <div className="p-4">
            <div className="flex items-center mb-2">
              <Image
                alt="Logo"
                className="rounded-full mr-3"
                height={40}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width={40}
              />
              <div>
                <h3 className="text-lg font-medium">Tienda de Electrónicos</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Tecnología y Gadgets
                </p>
              </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Explora nuestra amplia gama de productos electrónicos y gadgets de
              última generación.
            </p>
            <Link
              className="inline-flex items-center justify-center px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-500 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200 dark:focus:ring-gray-300"
              href="#"
            >
              Ver más
            </Link>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md dark:bg-gray-900">
          <div className="p-4">
            <div className="flex items-center mb-2">
              <Image
                alt="Logo"
                className="rounded-full mr-3"
                height={40}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width={40}
              />
              <div>
                <h3 className="text-lg font-medium">Tienda de Deportes</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Equipamiento Deportivo
                </p>
              </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Encuentra todo lo que necesitas para tu actividad física favorita.
            </p>
            <Link
              className="inline-flex items-center justify-center px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-500 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200 dark:focus:ring-gray-300"
              href="#"
            >
              Ver más
            </Link>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md dark:bg-gray-900">
          <div className="p-4">
            <div className="flex items-center mb-2">
              <Image
                alt="Logo"
                className="rounded-full mr-3"
                height={40}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width={40}
              />
              <div>
                <h3 className="text-lg font-medium">Tienda de Juguetes</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Juegos y Entretenimiento
                </p>
              </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Descubre una amplia selección de juguetes y juegos para todas las
              edades.
            </p>
            <Link
              className="inline-flex items-center justify-center px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-500 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200 dark:focus:ring-gray-300"
              href="#"
            >
              Ver más
            </Link>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md dark:bg-gray-900">
          <div className="p-4">
            <div className="flex items-center mb-2">
              <Image
                alt="Logo"
                className="rounded-full mr-3"
                height={40}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width={40}
              />
              <div>
                <h3 className="text-lg font-medium">Tienda de Hogar</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Decoración y Muebles
                </p>
              </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Encuentra todo lo que necesitas para decorar y amueblar tu hogar.
            </p>
            <Link
              className="inline-flex items-center justify-center px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-500 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200 dark:focus:ring-gray-300"
              href="#"
            >
              Ver más
            </Link>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md dark:bg-gray-900">
          <div className="p-4">
            <div className="flex items-center mb-2">
              <Image
                alt="Logo"
                className="rounded-full mr-3"
                height={40}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width={40}
              />
              <div>
                <h3 className="text-lg font-medium">Tienda de Mascotas</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Alimentos y Accesorios
                </p>
              </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Encuentra todo lo que necesitas para el cuidado de tus mascotas.
            </p>
            <Link
              className="inline-flex items-center justify-center px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-500 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200 dark:focus:ring-gray-300"
              href="#"
            >
              Ver más
            </Link>
          </div>
        </div>
        <div className="bg-white rounded-lg shadow-md dark:bg-gray-900">
          <div className="p-4">
            <div className="flex items-center mb-2">
              <Image
                alt="Logo"
                className="rounded-full mr-3"
                height={40}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "40/40",
                  objectFit: "cover",
                }}
                width={40}
              />
              <div>
                <h3 className="text-lg font-medium">Tienda de Belleza</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Cosméticos y Cuidado Personal
                </p>
              </div>
            </div>
            <p className="text-gray-600 dark:text-gray-400 mb-4">
              Encuentra una amplia selección de productos de belleza y cuidado
              personal.
            </p>
            <Link
              className="inline-flex items-center justify-center px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-500 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200 dark:focus:ring-gray-300"
              href="#"
            >
              Ver más
            </Link>
          </div>
        </div>
      </div>
      <section className="mt-8">
        <h2 className="text-xl font-bold mb-4">Filtros</h2>
        <div className="flex items-center space-x-4">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline">
                Categoría
                <ChevronDownIcon className="w-4 h-4 ml-2" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="start">
              <DropdownMenuCheckboxItem checked>Ropa</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Libros</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Electrónicos</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Deportes</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Juguetes</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Hogar</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Mascotas</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Belleza</DropdownMenuCheckboxItem>
            </DropdownMenuContent>
          </DropdownMenu>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline">
                Ubicación
                <ChevronDownIcon className="w-4 h-4 ml-2" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="start">
              <DropdownMenuCheckboxItem checked>
                Centro
              </DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Norte</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Sur</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Este</DropdownMenuCheckboxItem>
              <DropdownMenuCheckboxItem>Oeste</DropdownMenuCheckboxItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </section>
      <section className="mt-8">
        <h2 className="text-xl font-bold mb-4">Búsqueda Filtrada</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
          <div className="bg-white rounded-lg shadow-md dark:bg-gray-900">
            <div className="p-4">
              <div className="flex items-center mb-2">
                <Image
                  alt="Logo"
                  className="rounded-full mr-3"
                  height={40}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "40/40",
                    objectFit: "cover",
                  }}
                  width={40}
                />
                <div>
                  <h3 className="text-lg font-medium">Tienda de Ropa</h3>
                  <p className="text-gray-500 dark:text-gray-400">
                    Ropa y Accesorios
                  </p>
                </div>
              </div>
              <p className="text-gray-600 dark:text-gray-400 mb-4">
                Descubre una amplia selección de ropa y accesorios de moda en
                nuestra tienda.
              </p>
              <Link
                className="inline-flex items-center justify-center px-4 py-2 bg-gray-900 text-white rounded-md hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-500 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200 dark:focus:ring-gray-300"
                href="#"
              >
                Ver más
              </Link>
            </div>
          </div>
          <div className="bg-white rounded-lg shadow-md dark:bg-gray-900">
            <div className="p-4">
              <div className="flex items-center mb-2">
                <Image
                  alt="Logo"
                  className="rounded-full mr-3"
                  height={40}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "40/40",
                    objectFit: "cover",
                  }}
                  width={40}
                />
                <div>
                  <h3 className="text-lg font-medium" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  );
}

function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}
