/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tl5loqzGim2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function Categories() {
  return (<>
    <header
      className="bg-white text-gray-900 py-4 px-6 flex items-center justify-between">
      <Link className="flex items-center gap-2" href="#">
        <ArrowLeftIcon className="h-5 w-5" />
        <span>Volver</span>
      </Link>
      <span className="font-medium">Categorias</span>
    </header>
    <main className="py-8 px-6">
      <div className="mb-6">
        <Button size="sm" variant="primary">
          Agregar Categoría
        </Button>
      </div>
      <div className="space-y-4">
        <div
          className="bg-white border rounded-lg p-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <FolderIcon className="h-6 w-6 text-gray-500" />
            <div>
              <h3 className="font-medium">Ropa</h3>
              <p className="text-gray-500 text-sm">10 productos</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button size="sm" variant="outline">
              <PencilIcon className="h-4 w-4" />
            </Button>
            <Button size="sm" variant="danger">
              <TrashIcon className="h-4 w-4" />
            </Button>
          </div>
        </div>
        <div
          className="bg-white border rounded-lg p-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <FolderIcon className="h-6 w-6 text-gray-500" />
            <div>
              <h3 className="font-medium">Electrónicos</h3>
              <p className="text-gray-500 text-sm">25 productos</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button size="sm" variant="outline">
              <PencilIcon className="h-4 w-4" />
            </Button>
            <Button size="sm" variant="danger">
              <TrashIcon className="h-4 w-4" />
            </Button>
          </div>
        </div>
        <div
          className="bg-white border rounded-lg p-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <FolderIcon className="h-6 w-6 text-gray-500" />
            <div>
              <h3 className="font-medium">Hogar</h3>
              <p className="text-gray-500 text-sm">15 productos</p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <Button size="sm" variant="outline">
              <PencilIcon className="h-4 w-4" />
            </Button>
            <Button size="sm" variant="danger">
              <TrashIcon className="h-4 w-4" />
            </Button>
          </div>
        </div>
      </div>
      <div className="mt-8">
        <h2 className="text-lg font-bold mb-4">Agregar/Editar Categoría</h2>
        <form className="bg-white border rounded-lg p-6 space-y-4">
          <div>
            <Label htmlFor="name">Nombre</Label>
            <Input id="name" placeholder="Ingresa el nombre de la categoría" type="text" />
          </div>
          <div>
            <Label htmlFor="description">Descripción</Label>
            <Textarea id="description" placeholder="Ingresa la descripción de la categoría" />
          </div>
          <div className="flex justify-end gap-2">
            <Button variant="outline">Cancelar</Button>
            <Button variant="primary">Guardar</Button>
          </div>
        </form>
      </div>
    </main>
  </>);
}

function ArrowLeftIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>)
  );
}


function FolderIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z" />
    </svg>)
  );
}


function PencilIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
      <path d="m15 5 4 4" />
    </svg>)
  );
}


function TrashIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>)
  );
}
