/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xS8OsR6LCeL
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Oswald } from 'next/font/google'
import { Chivo } from 'next/font/google'

oswald({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import {
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { SheetTrigger, SheetContent, Sheet } from "@/components/ui/sheet";

export function HomePage() {
  return (
    <>
      <header className="flex items-center justify-between px-4 py-3 bg-gray-100 dark:bg-gray-800">
        <Link
          className="flex items-center gap-2 font-semibold text-gray-900 dark:text-gray-50"
          href="#"
        >
          <Package2Icon className="h-6 w-6" />
          <span>Acme Shop</span>
        </Link>
        <nav className="hidden md:flex items-center gap-4">
          <Link
            className="text-sm font-medium hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-50"
            href="#"
          >
            Home
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-50"
            href="#"
          >
            Products
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-50"
            href="#"
          >
            About
          </Link>
          <Link
            className="text-sm font-medium hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-50"
            href="#"
          >
            Reservation
          </Link>
          <div className="relative">
            <Select>
              <SelectTrigger className="flex items-center gap-2 text-sm font-medium hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-50">
                <span>USD</span>
                <ChevronDownIcon className="h-4 w-4" />
              </SelectTrigger>
              <SelectContent className="w-40">
                <SelectItem value="usd">USD</SelectItem>
                <SelectItem value="eur">EUR</SelectItem>
                <SelectItem value="gbp">GBP</SelectItem>
                <SelectItem value="jpy">JPY</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </nav>
        <Sheet>
          <SheetTrigger asChild>
            <Button className="md:hidden" size="icon" variant="outline">
              <MenuIcon className="h-6 w-6" />
              <span className="sr-only">Toggle menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="right">
            <div className="grid gap-4 p-4">
              <div className="flex items-center gap-2 font-semibold text-gray-900 dark:text-gray-50">
                <Package2Icon className="h-6 w-6" />
                <span>Acme Shop</span>
              </div>
              <Link
                className="text-sm font-medium hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                Home
              </Link>
              <Link
                className="text-sm font-medium hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                Products
              </Link>
              <Link
                className="text-sm font-medium hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                About
              </Link>
              <Link
                className="text-sm font-medium hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                Reservation
              </Link>
              <div className="relative">
                <Select>
                  <SelectTrigger className="flex items-center gap-2 text-sm font-medium hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-50">
                    <span>USD</span>
                    <ChevronDownIcon className="h-4 w-4" />
                  </SelectTrigger>
                  <SelectContent className="w-40">
                    <SelectItem value="usd">USD</SelectItem>
                    <SelectItem value="eur">EUR</SelectItem>
                    <SelectItem value="gbp">GBP</SelectItem>
                    <SelectItem value="jpy">JPY</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div className="bg-gray-800 p-4 rounded-lg flex items-center justify-center">
                <Link
                  className="text-sm font-medium hover:underline underline-offset-4 text-gray-400 hover:text-gray-50"
                  href="#"
                >
                  Admin
                </Link>
              </div>
            </div>
          </SheetContent>
        </Sheet>
      </header>
      <main>
        <section className="w-full py-6 md:py-8 lg:py-10 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Welcome to Acme Shop, your one-stop destination for high-quality
              products and exciting events. Explore our wide range of offerings
              and be a part of our vibrant community.
            </p>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container grid md:grid-cols-2 gap-8 px-4 md:px-6">
            <div className="flex flex-col items-start justify-center space-y-4">
              <div className="inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm font-medium dark:bg-gray-700 dark:text-gray-300">
                Upcoming Events
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Join Us for Exciting Events
              </h2>
              <p className="max-w-[500px] text-gray-500 md:text-xl dark:text-gray-400">
                Check out our upcoming events and be a part of the Acme
                community.
              </p>
              <Button className="mt-4" variant="link">
                View Events
              </Button>
            </div>
            <div className="flex justify-center">
              <Image
                alt="Acme Events"
                className="aspect-square object-cover rounded-lg"
                height={500}
                src="/placeholder.svg"
                width={500}
              />
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-6 px-4 md:px-6">
            <div className="flex flex-col items-start justify-center space-y-4">
              <Image
                alt="Offer 1"
                className="aspect-square object-cover rounded-lg"
                height={300}
                src="/placeholder.svg"
                width={300}
              />
              <div className="inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm font-medium dark:bg-gray-700 dark:text-gray-300">
                Special Offer
              </div>
              <div className="inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm font-medium dark:bg-gray-700 dark:text-gray-300">
                Tee
              </div>
              <h3 className="text-xl font-bold tracking-tighter">
                Acme Prism Tee
              </h3>
              <p className="text-gray-500 md:text-base dark:text-gray-400">
                Introducing the Acme Prism T-Shirt, a perfect blend of style and
                comfort.
              </p>
              <Button className="mt-2">Buy Now</Button>
            </div>
            <div className="flex flex-col items-start justify-center space-y-4">
              <Image
                alt="Offer 2"
                className="aspect-square object-cover rounded-lg"
                height={300}
                src="/placeholder.svg"
                width={300}
              />
              <div className="inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm font-medium dark:bg-gray-700 dark:text-gray-300">
                Special Offer
              </div>
              <div className="inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm font-medium dark:bg-gray-700 dark:text-gray-300">
                Backpack
              </div>
              <h3 className="text-xl font-bold tracking-tighter">
                Acme Backpack
              </h3>
              <p className="text-gray-500 md:text-base dark:text-gray-400">
                Durable and stylish backpack for everyday use.
              </p>
              <Button className="mt-2">Buy Now</Button>
            </div>
            <div className="flex flex-col items-start justify-center space-y-4">
              <Image
                alt="Offer 3"
                className="aspect-square object-cover rounded-lg"
                height={300}
                src="/placeholder.svg"
                width={300}
              />
              <div className="inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm font-medium dark:bg-gray-700 dark:text-gray-300">
                Special Offer
              </div>
              <div className="inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm font-medium dark:bg-gray-700 dark:text-gray-300">
                Water Bottle
              </div>
              <h3 className="text-xl font-bold tracking-tighter">
                Acme Water Bottle
              </h3>
              <p className="text-gray-500 md:text-base dark:text-gray-400">
                Reusable and eco-friendly water bottle.
              </p>
              <Button className="mt-2">Buy Now</Button>
            </div>
            <div className="flex flex-col items-start justify-center space-y-4">
              <Image
                alt="Offer 4"
                className="aspect-square object-cover rounded-lg"
                height={300}
                src="/placeholder.svg"
                width={300}
              />
              <div className="inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm font-medium dark:bg-gray-700 dark:text-gray-300">
                Special Offer
              </div>
              <div className="inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm font-medium dark:bg-gray-700 dark:text-gray-300">
                Sunglasses
              </div>
              <h3 className="text-xl font-bold tracking-tighter">
                Acme Sunglasses
              </h3>
              <p className="text-gray-500 md:text-base dark:text-gray-400">
                Stylish and durable sunglasses for any occasion.
              </p>
              <Button className="mt-2">Buy Now</Button>
            </div>
            <div className="flex flex-col items-start justify-center space-y-4">
              <Image
                alt="Offer 5"
                className="aspect-square object-cover rounded-lg"
                height={300}
                src="/placeholder.svg"
                width={300}
              />
              <div className="inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm font-medium dark:bg-gray-700 dark:text-gray-300">
                Special Offer
              </div>
              <div className="inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm font-medium dark:bg-gray-700 dark:text-gray-300">
                Tote Bag
              </div>
              <h3 className="text-xl font-bold tracking-tighter">
                Acme Tote Bag
              </h3>
              <p className="text-gray-500 md:text-base dark:text-gray-400">
                Versatile and stylish tote bag for everyday use.
              </p>
              <Button className="mt-2">Buy Now</Button>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container grid md:grid-cols-2 gap-8 px-4 md:px-6">
            <div className="flex flex-col items-start justify-center space-y-4">
              <div className="inline-block rounded-lg bg-gray-200 px-3 py-1 text-sm font-medium dark:bg-gray-700 dark:text-gray-300">
                About Acme Shop
              </div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Discover Our Collection
              </h2>
              <p className="max-w-[500px] text-gray-500 md:text-xl dark:text-gray-400">
                Explore our wide range of high-quality products, carefully
                curated to meet your needs.
              </p>
              <Button className="mt-4" variant="link">
                Explore Products
              </Button>
            </div>
            <div className="flex justify-center">
              <Image
                alt="Acme Shop"
                className="aspect-square object-cover rounded-lg"
                height={500}
                src="/placeholder.svg"
                width={500}
              />
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t bg-gray-100 dark:bg-gray-800">
        <p className="text-xs text-gray-500 dark:text-gray-400">
          © 2024 Acme Shop. All rights reserved.
        </p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link
            className="text-xs hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-50"
            href="#"
          >
            Terms of Service
          </Link>
          <Link
            className="text-xs hover:underline underline-offset-4 dark:text-gray-400 dark:hover:text-gray-50"
            href="#"
          >
            Privacy
          </Link>
        </nav>
      </footer>
    </>
  );
}

function ChevronDownIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  );
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function Package2Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  );
}
