/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/4DAZe6QXjHa
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function LoadingPage() {
  return (
    (<div className="flex items-center justify-center h-screen">
      <div className="space-y-4 text-center">
        <div className="text-3xl font-bold">Cargando</div>
        <div className="flex items-center justify-center space-x-2">
          <div className="w-4 h-4 bg-gray-500 rounded-full animate-bounce" />
          <div
            className="w-4 h-4 bg-gray-500 rounded-full animate-bounce animation-delay-100" />
          <div
            className="w-4 h-4 bg-gray-500 rounded-full animate-bounce animation-delay-200" />
        </div>
      </div>
    </div>)
  );
}
