/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7DXAqssbGw3
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  SelectValue,
  SelectTrigger,
  SelectItem,
  SelectContent,
  Select,
} from "@/components/ui/select";

export function Profile() {
  return (
    <>
      <header className="bg-white shadow-sm">
        <div className="container mx-auto flex items-center justify-between py-4 px-6">
          <div className="flex items-center gap-2">
            <Link className="flex items-center gap-2" href="#">
              <ArrowLeftIcon className="h-5 w-5" />
              <span className="text-sm font-medium">Back</span>
            </Link>
          </div>
        </div>
      </header>
      <main className="container mx-auto py-12 px-6">
        <form className="space-y-8">
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
            <div>
              <Label htmlFor="cover-photo">Cover Photo</Label>
              <div className="mt-1 flex justify-center rounded-md border-2 border-dashed border-gray-300 px-6 pt-5 pb-6">
                <div className="space-y-1 text-center">
                  <UploadIcon className="mx-auto h-12 w-12 text-gray-400" />
                  <div className="flex text-sm text-gray-600">
                    <label
                      className="relative cursor-pointer rounded-md bg-white font-medium text-indigo-600 focus-within:outline-none focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 hover:text-indigo-500"
                      htmlFor="cover-photo"
                    >
                      <span>Upload a file</span>
                      <Input
                        className="sr-only"
                        id="cover-photo"
                        name="cover-photo"
                        type="file"
                      />
                    </label>
                    <p className="pl-1">or drag and drop</p>
                  </div>
                  <p className="text-xs text-gray-500">
                    PNG, JPG, GIF up to 10MB
                  </p>
                </div>
              </div>
            </div>
            <div>
              <div className="space-y-2">
                <Label htmlFor="website-name">Website Name</Label>
                <Input
                  id="website-name"
                  name="website-name"
                  placeholder="Enter website name"
                  type="text"
                />
              </div>
              <div className="space-y-2 mt-4">
                <Label htmlFor="business-name">Business Name</Label>
                <Input
                  id="business-name"
                  name="business-name"
                  placeholder="Enter business name"
                  type="text"
                />
              </div>
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="welcome-message">Welcome Message</Label>
            <Textarea
              id="welcome-message"
              name="welcome-message"
              placeholder="Enter welcome message"
              rows={3}
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="info-message">Information Message</Label>
            <Textarea
              id="info-message"
              name="info-message"
              placeholder="Enter information message"
              rows={3}
            />
          </div>
          <div className="space-y-4">
            <div>
              <Label htmlFor="business-hours">Business Hours</Label>
              <div className="mt-2 grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3">
                <div>
                  <Label
                    className="block text-sm font-medium text-gray-700"
                    htmlFor="monday"
                  >
                    Monday
                  </Label>
                  <div className="mt-1 flex rounded-md shadow-sm">
                    <Select
                      className="block w-full rounded-md border-gray-300 text-gray-900 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                      defaultValue="24-hours"
                      id="monday"
                      name="monday"
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select option" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="24-hours">24 Hours</SelectItem>
                        <SelectItem value="closed">Closed</SelectItem>
                        <SelectItem value="custom">Custom Hours</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <div>
                  <Label
                    className="block text-sm font-medium text-gray-700"
                    htmlFor="tuesday"
                  >
                    Tuesday
                  </Label>
                  <div className="mt-1 flex rounded-md shadow-sm">
                    <Select
                      className="block w-full rounded-md border-gray-300 text-gray-900 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                      defaultValue="24-hours"
                      id="tuesday"
                      name="tuesday"
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select option" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="24-hours">24 Hours</SelectItem>
                        <SelectItem value="closed">Closed</SelectItem>
                        <SelectItem value="custom">Custom Hours</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <div>
                  <Label
                    className="block text-sm font-medium text-gray-700"
                    htmlFor="wednesday"
                  >
                    Wednesday
                  </Label>
                  <div className="mt-1 flex rounded-md shadow-sm">
                    <Select
                      className="block w-full rounded-md border-gray-300 text-gray-900 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                      defaultValue="24-hours"
                      id="wednesday"
                      name="wednesday"
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select option" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="24-hours">24 Hours</SelectItem>
                        <SelectItem value="closed">Closed</SelectItem>
                        <SelectItem value="custom">Custom Hours</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <div>
                  <Label
                    className="block text-sm font-medium text-gray-700"
                    htmlFor="thursday"
                  >
                    Thursday
                  </Label>
                  <div className="mt-1 flex rounded-md shadow-sm">
                    <Select
                      className="block w-full rounded-md border-gray-300 text-gray-900 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                      defaultValue="24-hours"
                      id="thursday"
                      name="thursday"
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select option" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="24-hours">24 Hours</SelectItem>
                        <SelectItem value="closed">Closed</SelectItem>
                        <SelectItem value="custom">Custom Hours</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <div>
                  <Label
                    className="block text-sm font-medium text-gray-700"
                    htmlFor="friday"
                  >
                    Friday
                  </Label>
                  <div className="mt-1 flex rounded-md shadow-sm">
                    <Select
                      className="block w-full rounded-md border-gray-300 text-gray-900 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                      defaultValue="24-hours"
                      id="friday"
                      name="friday"
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select option" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="24-hours">24 Hours</SelectItem>
                        <SelectItem value="closed">Closed</SelectItem>
                        <SelectItem value="custom">Custom Hours</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <div>
                  <Label
                    className="block text-sm font-medium text-gray-700"
                    htmlFor="saturday"
                  >
                    Saturday
                  </Label>
                  <div className="mt-1 flex rounded-md shadow-sm">
                    <Select
                      className="block w-full rounded-md border-gray-300 text-gray-900 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                      defaultValue="24-hours"
                      id="saturday"
                      name="saturday"
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select option" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="24-hours">24 Hours</SelectItem>
                        <SelectItem value="closed">Closed</SelectItem>
                        <SelectItem value="custom">Custom Hours</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
                <div>
                  <Label
                    className="block text-sm font-medium text-gray-700"
                    htmlFor="sunday"
                  >
                    Sunday
                  </Label>
                  <div className="mt-1 flex rounded-md shadow-sm">
                    <Select
                      className="block w-full rounded-md border-gray-300 text-gray-900 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                      defaultValue="24-hours"
                      id="sunday"
                      name="sunday"
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select option" />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="24-hours">24 Hours</SelectItem>
                        <SelectItem value="closed">Closed</SelectItem>
                        <SelectItem value="custom">Custom Hours</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="opening-time">Opening Time</Label>
              <Input
                id="opening-time"
                name="opening-time"
                placeholder="Enter opening time"
                type="time"
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="closing-time">Closing Time</Label>
              <Input
                id="closing-time"
                name="closing-time"
                placeholder="Enter closing time"
                type="time"
              />
            </div>
          </div>
          <div className="flex justify-end">
            <Button
              className="bg-indigo-600 hover:bg-indigo-700 text-white font-medium py-2 px-4 rounded-md"
              type="submit"
            >
              Save Changes
            </Button>
          </div>
        </form>
      </main>
    </>
  );
}

function ArrowLeftIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m12 19-7-7 7-7" />
      <path d="M19 12H5" />
    </svg>
  );
}

function UploadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  );
}
