/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/mRtnI4FBwLW
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { SheetTrigger, SheetContent, Sheet } from "@/components/ui/sheet"
import { PopoverTrigger, PopoverContent, Popover } from "@/components/ui/popover"
import { Calendar } from "@/components/ui/calendar"
import { SelectValue, SelectTrigger, SelectItem, SelectContent, Select } from "@/components/ui/select"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"

export function Reservation() {
  return (
    (<div
      className="grid min-h-screen w-full overflow-hidden lg:grid-cols-[280px_1fr]">
      <div className="hidden border-r bg-gray-100/40 lg:block dark:bg-gray-800/40">
        <div className="flex flex-col gap-2">
          <div className="flex h-[60px] items-center px-6">
            <Link className="flex items-center gap-2 font-semibold" href="#">
              <MountainIcon className="h-6 w-6" />
              <span className="">WebShop</span>
            </Link>
          </div>
          <div className="flex-1">
            <nav className="grid items-start px-4 text-sm font-medium">
              <Link
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#">
                Home
              </Link>
              <Link
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#">
                Products
              </Link>
              <Link
                className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#">
                About
              </Link>
              <Link
                className="flex items-center gap-3 rounded-lg bg-gray-900 px-3 py-2 text-white transition-all hover:bg-gray-800 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-200"
                href="#">
                Reservation
              </Link>
            </nav>
          </div>
        </div>
      </div>
      <div className="flex flex-col">
        <header
          className="flex h-14 lg:h-[60px] items-center gap-4 border-b bg-gray-100/40 px-6 dark:bg-gray-800/40">
          <Link className="lg:hidden" href="#">
            <MountainIcon className="h-6 w-6" />
            <span className="sr-only">WebShop</span>
          </Link>
          <div className="flex-1">
            <h1 className="font-semibold text-lg">Reserve Your Table</h1>
          </div>
          <Sheet>
            <SheetTrigger asChild>
              <Button className="ml-auto lg:hidden" size="icon" variant="outline">
                <MenuIcon className="h-6 w-6" />
                <span className="sr-only">Toggle navigation menu</span>
              </Button>
            </SheetTrigger>
            <SheetContent side="left">
              <div className="flex flex-col gap-2 py-6">
                <Link className="flex w-full items-center py-2 text-lg font-semibold" href="#">
                  Home
                </Link>
                <Link className="flex w-full items-center py-2 text-lg font-semibold" href="#">
                  Products
                </Link>
                <Link className="flex w-full items-center py-2 text-lg font-semibold" href="#">
                  About
                </Link>
                <Link className="flex w-full items-center py-2 text-lg font-semibold" href="#">
                  Reservation
                </Link>
              </div>
            </SheetContent>
          </Sheet>
        </header>
        <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6">
          <div className="mx-auto w-full max-w-sm space-y-2">
            <form className="grid gap-4">
              <div className="flex gap-2">
                <Popover>
                  <PopoverTrigger asChild>
                    <Button className="w-full flex-col h-auto items-start" variant="outline">
                      <span className="font-semibold uppercase text-[0.65rem]">Date</span>
                      <span className="font-normal">4/2/2024</span>
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="p-0 max-w-[276px]">
                    <Calendar />
                  </PopoverContent>
                </Popover>
              </div>
              <Select>
                <SelectTrigger className="h-auto">
                  <SelectValue
                    placeholder={
                      <div className="flex flex-col items-start">
                        <span className="font-semibold uppercase text-[0.65rem]">Guests</span>
                        <span className="font-normal">2 people</span>
                      </div>
                    } />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="1">1 person</SelectItem>
                  <SelectItem value="2">2 people</SelectItem>
                  <SelectItem value="3">3 people</SelectItem>
                  <SelectItem value="4">4 people</SelectItem>
                  <SelectItem value="5">5 people</SelectItem>
                  <SelectItem value="6">6 people</SelectItem>
                </SelectContent>
              </Select>
              <div className="grid gap-4">
                <div
                  className="flex items-center justify-between rounded-lg bg-gray-200 p-4 dark:bg-gray-700">
                  <div>
                    <div className="font-semibold">6:00 PM</div>
                    <div className="text-sm text-gray-600 dark:text-gray-400">Available</div>
                  </div>
                  <Button
                    className="bg-gray-900 text-white hover:bg-gray-800 focus:ring-2 focus:ring-gray-700 focus:ring-offset-2 dark:focus:ring-gray-600"
                    size="sm"
                    variant="outline">
                    Reserve
                  </Button>
                </div>
                <div
                  className="flex items-center justify-between rounded-lg bg-gray-200 p-4 dark:bg-gray-700">
                  <div>
                    <div className="font-semibold">7:00 PM</div>
                    <div className="text-sm text-gray-600 dark:text-gray-400">Available</div>
                  </div>
                  <Button size="sm" variant="outline">
                    Reserve
                  </Button>
                </div>
                <div
                  className="flex items-center justify-between rounded-lg bg-gray-200 p-4 dark:bg-gray-700">
                  <div>
                    <div className="font-semibold">8:00 PM</div>
                    <div className="text-sm text-gray-600 dark:text-gray-400">Available</div>
                  </div>
                  <Button size="sm" variant="outline">
                    Reserve
                  </Button>
                </div>
                <div
                  className="flex items-center justify-between rounded-lg bg-gray-200 p-4 dark:bg-gray-700">
                  <div>
                    <div className="font-semibold">9:00 PM</div>
                    <div className="text-sm text-gray-600 dark:text-gray-400">Available</div>
                  </div>
                  <Button size="sm" variant="outline">
                    Reserve
                  </Button>
                </div>
              </div>
              <div className="grid gap-2">
                <Label className="text-base" htmlFor="specifications">
                  Specifications
                </Label>
                <Textarea
                  className="min-h-[100px]"
                  id="specifications"
                  placeholder="Enter any special requirements or preferences" />
              </div>
              <div className="flex flex-col gap-2 min-[400px]:flex-row">
                <Button
                  className="w-full h-12 bg-gray-900 text-white hover:bg-gray-800 focus:ring-2 focus:ring-gray-700 focus:ring-offset-2 dark:focus:ring-gray-600"
                  size="lg">
                  Reserve
                </Button>
              </div>
            </form>
          </div>
        </main>
      </div>
    </div>)
  );
}

function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
